name: Deploy API to WSO2 APIM on macOS 

on:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install apictl
        run: |
         # Download the tarball
         curl -L -o apictl.tar.gz https://github.com/wso2/product-apim-tooling/releases/download/v4.4.0/apictl-4.4.0-darwin-arm64.tar.gz
         # Extract the tarball
         tar -xzvf apictl.tar.gz
         # List the extracted files to check the structure
          ls -la
           # Check if the binary is extracted directly or inside a folder
           if [ -f "./apictl" ]; then
             echo "Found apictl binary in current directory."
           sudo mv ./apictl /usr/local/bin/apictl
           elif [ -f "./apictl/apictl" ]; then
             echo "Found apictl binary in the apictl folder."
            sudo mv ./apictl/apictl /usr/local/bin/apictl
           else
            echo "apictl binary not found!"
           exit 1
           fi
           # Make the binary executable
           chmod +x /usr/local/bin/apictl
           # Update PATH for this step and subsequent steps
           export PATH=/usr/local/bin:$PATH
           echo "/usr/local/bin" >> $GITHUB_PATH
           # Verify installation
           apictl version
           export APICTL_TIMEOUT=120

      - name: Check network connectivity
        run: |
         ping -c 4 520e-203-94-95-14.ngrok-free.app
         
      - name: Check APIM URL
        run: |
         curl -I https://520e-203-94-95-14.ngrok-free.app

      - name: List contents of current directory
        run: ls -la
      
      - name: Configure APIM environment
        run: |
          #apictl remove env dev || true
          export APICLIENT_TIMEOUT=120

          apictl add env dev --apim https://520e-203-94-95-14.ngrok-free.app
      - name: Login to APIM
        run: |
           #curl -k https://dev.wso2shashika.com:9443/publisher
           apictl version
           echo "admin" | apictl login dev --insecure -u admin --password-stdin -k
      - name: Import API project
        run: |
          apictl import api --file ./SampleAPI --environment dev -k --rotate-revision
    
