name: Deploy API to WSO2 APIM on macOS

on:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install apictl
        run: |
          curl -L -o apictl.tar.gz https://github.com/wso2/product-apim-tooling/releases/download/v4.4.0/apictl-4.4.0-darwin-arm64.tar.gz
          tar -xzvf apictl.tar.gz
          echo "$(cwd)"

          chmod +x apictl
          echo "$(pwd)"
          export PATH=$PATH:/Users/runner/work/apictl/apictl
          echo "$PATH"

      - name: List contents of current directory
        run: ls -la
      

      - name: Configure APIM environment
        run: |
          apictl remove-env dev || true
          apictl add env dev --apim https://localhost:9443

      - name: Login to APIM
        run: |
          apictl login dev --insecure -u ${{ secrets.APIM_USERNAME }} -p ${{ secrets.APIM_PASSWORD }}

      - name: Import API project
        run: |
          apictl import api --file ./SampleAPI --environment dev -k --rotate-revision
