name: Deploy API to WSO2 APIM on macOS

on:
  push:
    branches: [ main ]

jobs:
  deploy-api:
    runs-on: macos-latest

    steps:
      - name: Clone repository using git clone
        run: |
          git clone https://github.com/shashikab/apictl.git
      - name: Configure APIM environment
        run: |
          apictl remove-env dev || true
          apictl add env dev --apim https://localhost:9443

      - name: Login to APIM
        run: |
          apictl login dev --insecure -u ${{ secrets.APIM_USERNAME }} -p ${{ secrets.APIM_PASSWORD }}

      - name: Import API project
        run: |
          apictl import api --file ./SampleAPI --environment dev -k --rotate-revision
